
name: Deploy to Amazon EC2

on:
  push:
    branches:
      - release

env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET_NAME: soomtut-github-actions-s3-bucket
  CODE_DEPLOY_APPLICATION_NAME: soomtut-back-deployment-app
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: soomtut-back-deployment-group
  
permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    # (1) 기본 체크아웃
    - name: Checkout
      uses: actions/checkout@v3

    # (2) JDK 17 세팅
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # (3) Gradle build (Test 제외)
    - name: Build with Gradle
      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      with:
        arguments: clean build -x test

    - name: zip create
      run: zip -r -qq ./SOOMTUT_BACK.zip .
      shell: bash

    # (4) AWS 인증 (IAM 사용자 Access Key, Secret Key 활용)
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # (5) 빌드 결과물을 S3 버킷에 업로드
    - name: Upload to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run:
        aws s3 cp --region ap-northeast-2 ./SOOMTUT_BACK.zip s3://soomtut-github-actions-s3-bucket/SOOMTUT_BACK.zip
    

    # (6) S3 버킷에 있는 파일을 대상으로 CodeDeploy 실행
    - name: Deploy to EC2 from S3
      run: aws deploy create-deployment 
        --application-name soomtut-back-deployment-app 
        --deployment-config-name CodeDeployDefault.AllAtOnce 
        --deployment-group-name soomtut-back-deployment-group 
        --s3-location bucket=soomtut-github-actions-s3-bucket,key=SOOMTUT_BACK.zip,bundleType=zip
